import Form from "./components/Form";
import Navbar from "./components/Navbar";
import "./globals.css";
import { Inter, Oswald, Poppins } from "next/font/google";

const poppins = Poppins({ subsets: ["latin"], weight: '400' });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} relative`}>

        <main className="h-screen grid md:grid-cols-12  md:grid-rows-12">
          <div className="  md:row-span-12 md:col-span-1">
            <Navbar />
          </div>

          <div className=" md:col-span-11 md:row-span-12 overflow-y-auto p-5 md:p-16">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
